#Removes the "Allow Cheats" button in the "Open to LAN" screen, if set to "true".
removeButtonInOpenToLANScreen = false
#Removes the "Allow Cheats" button in the "Create New World" screen, if set to "true".
removeButtonInCreateNewWorldScreen = true

