#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Mar 07 18:17:43 EET 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.4.zip
enableShaders=false
